name: Publish Docker image
on:
  push:
    branches:
      - cicd
    tags: 
      - v*
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}  # maybe use GITHUB_TOKEN ?
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{  github.repository_owner }}/my-image  # change to  github.event.repository.name  
          tags: |
            type=raw,value=${{ github.run_number }}
            type=ref,event=tag
            type=sha

      - name: Build and push Docker image
        id: buildandpush
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  deploy:
    runs-on: ubuntu-20.04
    needs: build-and-push
    environment: test-frontend-zminec
    env:
      FRONTEND_IMAGE_TAG:  ${{needs.build-and-push.outputs.output1}}
      FRONTEND_TEST: "testing FRONTEND"
    steps:
    - name: deploy to server
      uses: garygrossgarten/github-action-ssh@0.8.0
      with:
        command: env |grep FRONTEND
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.PRIVATE_KEY}}